import { Contact } from 'src/app/models/contactdata';

export const contacts: Contact[] =
[
    {'id': 1, 'firstName' : 'Luck', 'lastName' : 'Bach', 'position': 'Graphics Designer' , 'address' : 'Rivera State 32/106',
     'imageUrl': 'assets/alex jonathan.jpg',
     companyName: 'Twitter Inc. ',
     companyAddrss: '795 Follsom Avenu, Suite 600', 
     companyCity: 'San Francisco',
     companyState: 'CA',
     companyZip: '94107',
     companyPhone: '(123) 456-790 ',
     },
    {'id': 2, 'firstName' : 'Silvan', 'lastName' : 'Bach', 'position': 'CEO' , 'address' : 'Rivera State 32/106',
     'imageUrl': 'assets/janeth carton.jpg',
     companyName: 'Twitter Inc. ',
     companyAddrss: '795 Follsom Avenu, Suite 600', 
     companyCity: 'San Francisco',
     companyState: 'CA',
     companyZip: '94107',
     companyPhone: '(123) 456-790 ',
    },
    {'id': 3, 'firstName' : 'Pico', 'lastName' : 'Bach', 'position': 'Marketing Manager' , 'address' : 'Rivera State 32/106',
     'imageUrl': 'assets/john-smith.jpg',
     companyName: 'Twitter Inc. ',
     companyAddrss: '795 Follsom Avenu, Suite 600', 
     companyCity: 'San Francisco',
     companyState: 'CA',
     companyZip: '94107',
     companyPhone: '(123) 456-790 ',
    },
    {'id': 4, 'firstName' : 'Dell', 'lastName' : 'Bach', 'position': 'Graphics Designer' , 'address' : 'Rivera State 32/106',
         'imageUrl': 'assets/michael zimber.jpg',
         companyName: 'Twitter Inc. ',
         companyAddrss: '795 Follsom Avenu, Suite 600', 
         companyCity: 'San Francisco',
         companyState: 'CA',
         companyZip: '94107',
         companyPhone: '(123) 456-790 ',
        },
    {'id': 5, 'firstName' : 'Stan', 'lastName' : 'Bach', 'position': 'Graphics Designer' , 'address' : 'Rivera State 32/106',
    'imageUrl': 'assets/monica smith.jpg',
    companyName: 'Twitter Inc. ',
    companyAddrss: '795 Follsom Avenu, Suite 600', 
    companyCity: 'San Francisco',
    companyState: 'CA',
    companyZip: '94107',
    companyPhone: '(123) 456-790 ',
    },
    {'id': 6, 'firstName' : 'Ron', 'lastName' : 'Bach', 'position': 'Graphics Designer' , 'address' : 'Rivera State 32/106',
    'imageUrl': 'assets/sandra smith.jpg',
    companyName: 'Twitter Inc. ',
    companyAddrss: '795 Follsom Avenu, Suite 600', 
    companyCity: 'San Francisco',
    companyState: 'CA',
    companyZip: '94107',
    companyPhone: '(123) 456-790 ',
    },
];
